# Generated by Django 3.2.3 on 2021-06-05 10:02

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_rename_addphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='Maximum file size allowed is 2Mb', upload_to='addphoto', validators=[photos.models.validate_image]),
        ),
    ]
